#ifndef _UTIL_H_
#define _UTIL_H_


// Log Setting
#define PRINT_INITIAL_SEQUENCE_PAIR true

// Simulated Annealing Setting
#define ANNEALING_TEMPERATURE 999999
#define CRITICAL_TEMPERATURE 999
#define TEMPERATURE_DECREASING_SLOW_RATE 0.999
#define TEMPERATURE_DECREASING_FAST_RATE 0.5
#define TERMINATE_TEMPERATURE 1
#define STEPS_PER_TEMPERATURE 300
#define MAX_CONSECUTIVE_TEMPERATURN_UNCHANGE 15

#define OPERATION1 0
#define OPERATION2 1
#define OPERATION3 2
#define OPERATION4 3

#define ACCEPT 1
#define REJECT 0

struct Match{
    size_t X;
    size_t Y;
};

#endif